from google import genai
from google.genai import types
from src.tools.profile_tool import ProfileAnalysisTool
from src.agents.api_utils import generate_content_with_retry
import os

class ProfileAnalysisAgent:
    """
    Agent 1: Profile Analysis Agent
    Responsible for understanding the user's current skills and career goals,
    structuring them clearly for downstream agents by using the profile tool.
    """
    def __init__(self, api_key: str = None):
        # Allow passing key directly, otherwise client attempts to grab from os.environ
        self.client = genai.Client(api_key=api_key or os.environ.get("GEMINI_API_KEY"))
        self.tool = ProfileAnalysisTool()
        
    def analyze(self, raw_skills_input: str, career_goal: str) -> dict:
        """
        Uses the Gemini model to parse a raw string of skills, extracting them into a clean array, 
        and invoking the structural Profile Tool to save the state.
        """
        prompt = (
            f"You are an expert Career Profile Analyst.\\n"
            f"User's raw skills input: '{raw_skills_input}'\\n"
            f"Target career goal: '{career_goal}'\\n\\n"
            f"Extract a comprehensive list of the user's skills. Use the `analyze_user_profile` "
            f"tool to structure this data."
        )
        
        # Provide the MCP-compliant schema block to the model
        gemini_tool = types.Tool(
            function_declarations=[
                types.FunctionDeclaration(
                    name=self.tool.name,
                    description=self.tool.description,
                    parameters=self.tool.schema
                )
            ]
        )
        
        try:
            response = generate_content_with_retry(
                client=self.client,
                contents=prompt,
                config=types.GenerateContentConfig(
                    tools=[gemini_tool],
                    tool_config=types.ToolConfig(
                        function_calling_config=types.FunctionCallingConfig(
                            mode="ANY",
                            allowed_function_names=[self.tool.name]
                        )
                    ),
                    temperature=0.1, # Low temperature for accurate extraction
                )
            )
            
            # Check if model properly invoked the defined tool
            if response.function_calls:
                for fn_call in response.function_calls:
                    if fn_call.name == self.tool.name:
                        # Parse the arguments generated by Gemini
                        args = fn_call.args
                        skills_list = args.get("skills", [])
                        goal = args.get("career_goal", career_goal)
                        
                        # Execute deterministic logic and return results
                        return self.tool.execute(skills=skills_list, career_goal=goal)
                        
            return {
                "error": "Failed to parse profile via tool extraction.",
                "raw_text": response.text
            }
        except Exception as e:
            return {
                "error": f"Agent failed due to API error: {str(e)}",
            }
